temp_collect = ['https://profiplitka.ru/plitka/absolut-gres/']
temp_collect2 = ['https://profiplitka.ru/plitka/abk-group/', 'https://profiplitka.ru/plitka/absolut-gres/',
                'https://profiplitka.ru/plitka/absolut-keramika/',
                'https://profiplitka.ru/plitka/alma-ceramica/', 'https://profiplitka.ru/plitka/altacera/',
                'https://profiplitka.ru/plitka/ametis-by-estima/', 'https://profiplitka.ru/plitka/anka-seramik/',
                'https://profiplitka.ru/plitka/aparici/', 'https://profiplitka.ru/plitka/apavisa/',
                'https://profiplitka.ru/plitka/ape-ceramica/',
                'https://profiplitka.ru/plitka/arcana-ceramica/', 'https://profiplitka.ru/plitka/argenta-ceramica/',
                'https://profiplitka.ru/plitka/art-ceramic/', 'https://profiplitka.ru/plitka/art-natura/',
                'https://profiplitka.ru/plitka/art-natura-ceramica/',
                'https://profiplitka.ru/plitka/asia-pacific-ceramic/', 'https://profiplitka.ru/plitka/atlas-concorde/',
                'https://profiplitka.ru/plitka/atlas-concorde-russia/', 'https://profiplitka.ru/plitka/atlas-plan/',
                'https://profiplitka.ru/plitka/axima/',
                'https://profiplitka.ru/plitka/azori/', 'https://profiplitka.ru/plitka/azteca/',
                'https://profiplitka.ru/plitka/azulejos-benadresa/', 'https://profiplitka.ru/plitka/baldocer/',
                'https://profiplitka.ru/plitka/belleza/', 'https://profiplitka.ru/plitka/belmar/',
                'https://profiplitka.ru/plitka/bestile/', 'https://profiplitka.ru/plitka/bien-seramik/',
                'https://profiplitka.ru/plitka/bisazza/',
                'https://profiplitka.ru/plitka/bonaparte/',
                'https://profiplitka.ru/plitka/caesar/', 'https://profiplitka.ru/plitka/carmen-ceramic-art/',
                'https://profiplitka.ru/plitka/casa-dolce-casa/', 'https://profiplitka.ru/plitka/casalgrande-padana/',
                'https://profiplitka.ru/plitka/casati-ceramica/', 'https://profiplitka.ru/plitka/cesi/',
                'https://profiplitka.ru/plitka/cedit/', 'https://profiplitka.ru/plitka/ceradim/',
                'https://profiplitka.ru/plitka/ceramica-classic/', 'https://profiplitka.ru/plitka/ceramiche-grazia/',
                'https://profiplitka.ru/plitka/ceramika-color/', 'https://profiplitka.ru/plitka/ceramika-konskie/',
                'https://profiplitka.ru/plitka/cerim/',
                'https://profiplitka.ru/plitka/cerrad/', 'https://profiplitka.ru/plitka/cersanit/',
                'https://profiplitka.ru/plitka/cifre-ceramica/',
                'https://profiplitka.ru/plitka/cir/',
                'https://profiplitka.ru/plitka/click-ceramica/', 'https://profiplitka.ru/plitka/codicer-95/',
                'https://profiplitka.ru/plitka/coliseumgres/', 'https://profiplitka.ru/plitka/colorker/',
                'https://profiplitka.ru/plitka/creto/', 'https://profiplitka.ru/plitka/cristacer/',
                'https://profiplitka.ru/plitka/cube-ceramica/', 'https://profiplitka.ru/plitka/decovita/',
                'https://profiplitka.ru/plitka/del-conca/', 'https://profiplitka.ru/plitka/delacora/',
                'https://profiplitka.ru/plitka/dna-tiles/', 'https://profiplitka.ru/plitka/domino/',
                'https://profiplitka.ru/plitka/dual-gres/',
                'https://profiplitka.ru/plitka/ecoceramic/',
                'https://profiplitka.ru/plitka/el-molino/',
                'https://profiplitka.ru/plitka/emigres/',
                'https://profiplitka.ru/plitka/equipe/', 'https://profiplitka.ru/plitka/estima/',
                'https://profiplitka.ru/plitka/etili-seramik/', 'https://profiplitka.ru/plitka/europa-ceramica/',
                'https://profiplitka.ru/plitka/fanal/', 'https://profiplitka.ru/plitka/fap-ceramiche/',
                'https://profiplitka.ru/plitka/floor-gres/', 'https://profiplitka.ru/plitka/fmg/',
                'https://profiplitka.ru/plitka/gayafores/',
                'https://profiplitka.ru/plitka/geotiles/', 'https://profiplitka.ru/plitka/global-tile/',
                'https://profiplitka.ru/plitka/golden-tile/',
                'https://profiplitka.ru/plitka/gracia-ceramica/', 'https://profiplitka.ru/plitka/grasaro/',
                'https://profiplitka.ru/plitka/grespania/', 'https://profiplitka.ru/plitka/gresse/',
                'https://profiplitka.ru/plitka/halcon-ceramicas/',
                'https://profiplitka.ru/plitka/harmony/',
                'https://profiplitka.ru/plitka/ibero-ceramicas/',
                'https://profiplitka.ru/plitka/idalgo/',
                'https://profiplitka.ru/plitka/imola-ceramica/', 'https://profiplitka.ru/plitka/impronta/',
                'https://profiplitka.ru/plitka/infinity-ceramica/', 'https://profiplitka.ru/plitka/irida-mosaic/',
                'https://profiplitka.ru/plitka/itaca/', 'https://profiplitka.ru/plitka/italica/',
                'https://profiplitka.ru/plitka/italon/', 'https://profiplitka.ru/plitka/itc/',
                'https://profiplitka.ru/plitka/itt-ceramic/',
                'https://profiplitka.ru/plitka/keope-ceramiche/', 'https://profiplitka.ru/plitka/keraben/',
                'https://profiplitka.ru/plitka/kerama-marazzi/', 'https://profiplitka.ru/plitka/keratile/',
                'https://profiplitka.ru/plitka/kerlife/', 'https://profiplitka.ru/plitka/kerranova/',
                'https://profiplitka.ru/plitka/korzilius/', 'https://profiplitka.ru/plitka/kutahya/',
                'https://profiplitka.ru/plitka/la-diva/', 'https://profiplitka.ru/plitka/la-fabbrica/',
                'https://profiplitka.ru/plitka/la-faenza/', 'https://profiplitka.ru/plitka/la-platera/',
                'https://profiplitka.ru/plitka/laminam/', 'https://profiplitka.ru/plitka/land-porcelanico/',
                'https://profiplitka.ru/plitka/laparet/', 'https://profiplitka.ru/plitka/lb-ceramics/',
                'https://profiplitka.ru/plitka/lcm/',
                'https://profiplitka.ru/plitka/love-ceramic-tiles/', 'https://profiplitka.ru/plitka/luxsera/',
                'https://profiplitka.ru/plitka/maciej-zien/', 'https://profiplitka.ru/plitka/maimoon/',
                'https://profiplitka.ru/plitka/mainzu/',
                'https://profiplitka.ru/plitka/marazzi/', 'https://profiplitka.ru/plitka/meissen-keramik/',
                'https://profiplitka.ru/plitka/monopole-ceramica/',
                'https://profiplitka.ru/plitka/neodom/', 'https://profiplitka.ru/plitka/newtrend/',
                'https://profiplitka.ru/plitka/pamesa-ceramica/',
                'https://profiplitka.ru/plitka/paradyz/', 'https://profiplitka.ru/plitka/peronda/',
                'https://profiplitka.ru/plitka/porcelanosa/', 'https://profiplitka.ru/plitka/prime-ceramics/',
                'https://profiplitka.ru/plitka/prissmacer/',
                'https://profiplitka.ru/plitka/qua-granite/', 'https://profiplitka.ru/plitka/ragno/',
                'https://profiplitka.ru/plitka/rak-ceramics/',
                'https://profiplitka.ru/plitka/realistik/', 'https://profiplitka.ru/plitka/realonda/',
                'https://profiplitka.ru/plitka/refin-ceramiche/', 'https://profiplitka.ru/plitka/rex-ceramiche/',
                'https://profiplitka.ru/plitka/roca/',
                'https://profiplitka.ru/plitka/sant-agostino/', 'https://profiplitka.ru/plitka/seramiksan/',
                'https://profiplitka.ru/plitka/serenissima/', 'https://profiplitka.ru/plitka/seron/',
                'https://profiplitka.ru/plitka/settecento/', 'https://profiplitka.ru/plitka/simpolo/',
                'https://profiplitka.ru/plitka/steppe-ceramics/', 'https://profiplitka.ru/plitka/stiles-ceramic/',
                'https://profiplitka.ru/plitka/stn-ceramica/', 'https://profiplitka.ru/plitka/sunhearrt-ceramic/',
                'https://profiplitka.ru/plitka/tagina-ceramiche/',
                'https://profiplitka.ru/plitka/terracottapro/',
                'https://profiplitka.ru/plitka/tubadzin/', 'https://profiplitka.ru/plitka/undefasa/',
                'https://profiplitka.ru/plitka/unitile-shakhtinskaja-plitka/',
                'https://profiplitka.ru/plitka/valentto/', 'https://profiplitka.ru/plitka/vallelunga/',
                'https://profiplitka.ru/plitka/villeroy-boch/', 'https://profiplitka.ru/plitka/vitacer/',
                'https://profiplitka.ru/plitka/vitra/', 'https://profiplitka.ru/plitka/westerwalder/',
                'https://profiplitka.ru/plitka/wow/', 'https://profiplitka.ru/plitka/yurtbay-seramik/',
                'https://profiplitka.ru/plitka/berezakeramika/',
                'https://profiplitka.ru/plitka/grani-taganaja/', 'https://profiplitka.ru/plitka/graniteja/',
                'https://profiplitka.ru/plitka/dst/',
                'https://profiplitka.ru/plitka/keramin/', 'https://profiplitka.ru/plitka/kerlajf/',
                'https://profiplitka.ru/plitka/kontakt/',
                'https://profiplitka.ru/plitka/nefrit-keramika/',
                'https://profiplitka.ru/plitka/sokol/',
                'https://profiplitka.ru/plitka/uralkeramika/',
                'https://profiplitka.ru/plitka/uralskij-granit/', 'https://profiplitka.ru/plitka/frilajt/']
